# Generated by Django 5.1.2 on 2024-12-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='mercedes s-class', max_length=150)),
                ('description', models.TextField(default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('write_time', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField()),
            ],
        ),
    ]
